---
name: "{{cookiecutter.project_name}}"
version: "{{ '{{major}}.{{minor}}.{{patch}}' }}"
description: "{{cookiecutter.description}}"
entry: {{ '{{entry}}' }}
requirements: []
dev_requirements:
  - vmklib
