name: "{{cookiecutter.project_name}}"
version: {{ '{{major}}.{{minor}}.{{patch}}' }}
description: "{{cookiecutter.description}}"
entry: {{ '{{entry}}' }}
setup_args:
- entry_override="{{ '{{entry}}' }}"
