---
name: {{cookiecutter.project_name}}
version: "{{ '{{major}}.{{minor}}.{{patch}}' }}"
description: {{cookiecutter.description}}
{%- if cookiecutter.has_cli|lower == "true" %}
entry: {{ '{{entry}}' }}
{%- endif %}
requirements:
  - vcorelib
dev_requirements:
  - setuptools-wrapper
  - types-setuptools
