---
author_info:
  name: {{cookiecutter.name}}
  email: {{cookiecutter.email}}
  username: {{cookiecutter.username}}
versions: ["3.8", "3.9", "3.10", "3.11"]

systems:
  - macos-latest
  - windows-latest
