---
name: Build Template

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ${{matrix.system}}
    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
        system:
          - macos-latest
          - windows-latest
          - ubuntu-latest

    env:
      PYTHON_VERSION: ${{matrix.python-version}}

    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive

      - uses: tlylt/install-graphviz@main

      - name: python${{matrix.python-version}} setup
        uses: actions/setup-python@main
        with:
          python-version: ${{matrix.python-version}}

      - name: install-mk
        run: pip${{matrix.python-version}} install vmklib

      - name: venv
        run: mk venv python-install-yamllint

      - name: test
        run: mk test yaml
