---
name: Build Template

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"

    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive
      - name: python${{matrix.python-version}} setup
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
      - uses: ts-graphviz/setup-graphviz@v1
      - name: install-mk
        run: |
          pip${{matrix.python-version}} install vmklib
      - name: venv
        run: |
          mk PYTHON_VERSION=${{matrix.python-version}} venv
      - name: test
        run: |
          mk PYTHON_VERSION=${{matrix.python-version}} test
